### ISSUE TITLE
Wrong adapter class with MariaDB

### ISSUE THREAD

**Issue by valerauko** [tomekw/hikari-cp#100]
Using the latest (3.0.8) MariaDB JDBC package, setting `:adapter` as `:mariadb` results in ClassNotFoundException org.mariadb.jdbc.MySQLDataSource. The class name in this version is MariaDbDataSource.

This issue can be worked around by using the `:jdbc-url` option instead of individual `:adapter` `:database-name` etc.

**Comment by tomekw** [comment]
@valerauko can this be fixed similar to this? :)

https://github.com/tomekw/hikari-cp/pull/101

**Comment by valerauko** [comment]
I don't think it should take any more than changing the MySQLDataSource to MariaDbDataSource.

However I don't know which version the name changed (or if there was a MariaDbDataSource all along?), so this might be a breaking change for older MariaDb versions

**Comment by tomekw** [comment]
I think it should be changed, see: https://github.com/brettwooldridge/HikariCP#popular-datasource-class-names

**Comment by valerauko** [comment]
I tried changing the class name, but MariaDbDataSource doesn't seem to support the databaseName option. Is this normal for a JDBC adapter?
