### ISSUE TITLE
hook on connection initialization

### ISSUE THREAD

**Issue by niquola** [tomekw/hikari-cp#14]
Hello, is there any way to be hooked when new connection is opened.

I have to do some initialization SQL before all queries, ala `SET plv8.init_proc =...`

**Comment by tomekw** [comment]
Hello @niquola, I believe you can use `:connection-init-sql` option.

**Comment by tomekw** [comment]
Anyway, let me know if it works for you, please. Also, the PR to update the README would be great! :)

**Comment by niquola** [comment]
Should this key be added to datasource-options and passed to (make-datasource opts) ?

`Method not found: setConnectionInitSql`

**Comment by niquola** [comment]
Also looks like ignoring: ```(.addDataSourceProperty ds "connectionInitSQL" "SET plv8.start_proc = 'plv8_init'") ```

**Comment by niquola** [comment]
```(.setConnectionInitSql config "SET plv8.ustart_proc = 'plv8_init';") ```  does not work too

**Comment by tomekw** [comment]
@niquola Weird: https://github.com/brettwooldridge/HikariCP/search?utf8=%E2%9C%93&q=setConnectionInitSql&type=Code

The solution would be to add custom setting like here:

https://github.com/tomekw/hikari-cp/blob/fd2bf0d5d760203e84a8290edb164de78dfafd73/src/hikari_cp/core.clj#L117-L125

Would you be so kind to prepare PR for this? :)

**Comment by niquola** [comment]
I will try

**Comment by tomekw** [comment]
:+1: Thanks!

**Comment by tomekw** [comment]
Ah, @niquola please look at https://github.com/tomekw/hikari-cp/pull/13 :) - got merged, I just need to release it to Clojars

**Comment by niquola** [comment]
Cool, 

The only problem - that i'm doing this by hand - but it does not work :(

Ie (.setConnectionInitSql config "SET plv8.ustart_proc = 'plv8_init';") is called without errors, but SQL statement does not executed.

**Comment by niquola** [comment]
Who should execute this statement - pool? driver?

**Comment by niquola** [comment]
Another question: how to set pg specific connection property 'stringtype=unspecified'?

**Comment by jstepien** [comment]
> Another question: how to set pg specific connection property 'stringtype=unspecified'?

Would it work for you to set it [using the `configure` option][cfg]? It would probably something along the lines of:

```clojure
(make-datasource {:configure (fn [cfg] (.setYourProperty ...))})
```

[cfg]: https://github.com/tomekw/hikari-cp/blob/de94afc11c82fb8333bb11b526dbe253071b5dc8/src/hikari_cp/core.clj#L132

**Comment by tomekw** [comment]
@niquola is there any way we can help you? :)

**Comment by jstepien** [comment]
Explicit support for `:connection-init-sql` has been added in 7fbe6acc6a31c52583b8890317e9b86c34850d43 and released in 1.6.0. I hope this helps!

**Comment by jjl** [comment]
It would be nice to have a hook for on connection too. I'm experimenting with postgres notifications and I need a reliable way to set them up. Since they might vary over the course of a program run, fixed sql isn't going to cut it :/

**Comment by jstepien** [comment]
@jjl Sure, if HikariCP supports it it'd be great to have it. Patches are very welcome!
