### ISSUE TITLE
additional configuration option: register-mbeans

### ISSUE THREAD

**Issue by Deepak-initcron** [tomekw/hikari-cp#21]
hello,
I am trying to enable jmx monitoring for hikari-cp. But register-mbeans to setRegisterMbeans is not currently present.
(.setRegisterMbeans register-mbeans)

**Comment by jstepien** [comment]
Hi!

Would it work for you to set it [using the `configure` option][cfg]? It would probably something along the lines of:

```clojure
(make-datasource {:configure (fn [cfg] (.setRegisterMbeans ...))})
```

[cfg]: https://github.com/tomekw/hikari-cp/blob/de94afc11c82fb8333bb11b526dbe253071b5dc8/src/hikari_cp/core.clj#L132

**Comment by jstepien** [comment]
Thanks for adding it in #22!
