### ISSUE TITLE
Fix Readme :jdbc-url should be :url

### ISSUE THREAD

**Issue by ivos** [tomekw/hikari-cp#26]
Got confused when trying to use :jdbc-url config param. Then I found out in the H2 example below that it should actually be :url.

**Comment by tomekw** [comment]
Thanks @ivos ! Please find the referenced PR.

**Comment by tomekw** [comment]
Ah, so it's other way around?

**Comment by ivos** [comment]
Yea, using H2 and :jdbc-url didn't work. After switching to :url it started to work.

A bit confusing for me, because the source indicate your work with :jdbc-url...

**Comment by ivos** [comment]
A working example: https://github.com/ivos/clojure-jdbc-sample/commit/c45b002306167419b9f7f4a6f45a8b88ebeb797d

In src/clojure_jdbc_sample/core.clj, lines 14 and 15.

Line 15 works. Line 14 says "No suitable driver found for ". Which indicates that the URL is actually an empty String.

**Comment by jstepien** [comment]
I've just tried it and I can confirm it; h2 works with `:url` but fails with `:jdbc-url`, just as reported by @ivos. The h2 example appears to be correct as of current master, 139704e24385bea3be13cb8ded4508d6daca548e. What we might need is a footnote in the _Configuration options_ table saying that h2 expects `:url`.

@tomekw should we close #28?

**Comment by tomekw** [comment]
@jstepien done! :)

**Comment by jstepien** [comment]
Thanks a lot! :)
