### ISSUE TITLE
ability to supply the datasource directly

### ISSUE THREAD

**Issue by yogthos** [tomekw/hikari-cp#32]
It would be nice to have an option to pass in a configured datasource or to provide a custom classname. I'm using hikari-cp in my [conman](https://github.com/luminus-framework/conman) library for Luminus. Currently, it's setup to accept `:datasource` and `:datasource-classname` keys. The datasource can be used instead of the jdbc-url and the adapter. Meanwhile, the datasource classname can be used with the jdbc-url to initialize a datasource.

**Comment by jstepien** [comment]
Sounds good. We'd love to see a patch introducing this change!

**Comment by yogthos** [comment]
sounds good, I'll take a look at doing a pr this

**Comment by jstepien** [comment]
Implemented in #34.
