### ISSUE TITLE
inconsistent naming of options

### ISSUE THREAD

**Issue by jjl** [tomekw/hikari-cp#46]
`:datasource-classname` and `:driver-class-name` are inconsistently formatted.

**Comment by tomekw** [comment]
Oh, that's unfortunate :( Thank you for bringing this. @jstepien WDYT about changing this in 1.8.0? Or 2.0.0? I will be happy to unify this.

**Comment by jstepien** [comment]
Sure, I'd be happy to accept a patch fixing it. Not to break existing clients I'd love to have it support both `: datasource-classname` and `: datasource-class-name` and release it as 1.8.0.

**Comment by tomekw** [comment]
Yes, this also a way to go /cc @jjl

**Comment by jjl** [comment]
I think I can probably submit a PR for that once I've got the work that caused me to notice this out of the way.

**Comment by jstepien** [comment]
Perfect! No rush.

**Comment by tomekw** [comment]
@jjl still able submit a PR? :)
