### ISSUE TITLE
MetricsRegistry is erroneously forwarded to the datasource

### ISSUE THREAD

**Issue by sebastianpoeplau** [tomekw/hikari-cp#48]
When the option `:metric-registry` is specified in a call to `datasource-config`, hikari-cp attempts to set the property "metricRegistry" in the datasource instead of just setting the registry in HikariConfig, which fails at least for Postgres.

The reason, I believe, is that `datasource-config` [fails](https://github.com/tomekw/hikari-cp/blob/master/src/hikari_cp/core.clj#L143) to remove `:metric-registry` from the options before setting datasource properties. Will submit a PR...

**Comment by gaczm** [comment]
@tomekw @jstepien  Can you release new version with this fix included?

**Comment by tomekw** [comment]
@gaczm sure, I will do this in the evening unless @jstepien will be first :)

**Comment by jstepien** [comment]
Sure, I'll try to publish a release over the weekend.

**Comment by jstepien** [comment]
> @gaczm sure, I will do this in the evening unless @jstepien will be first :)

All yours, Tomek :)

**Comment by gaczm** [comment]
thanks :)

**Comment by tomekw** [comment]
@gaczm done!
