### ISSUE TITLE
MySQL error: classnotfound

### ISSUE THREAD

**Issue by WorldsEndless** [tomekw/hikari-cp#63]
Using 
```
; project.clj
; ...
                 [hikari-cp "1.8.1"]
                 [mysql/mysql-connector-java "8.0.7-dmr"]
; ...
```

```
ns> (-> env :db)
{:database-name "humhelp", :adapter "mysql", :auto-commit true, :register-mbeans false, :password "humhelp", :username "humhelp", :max-lifetime 1800000, :minimum-idle 10, :connection-timeout 30000, :server-name "localhost", :read-only false, :maximum-pool-size 10, :idle-timeout 600000, :validation-timeout 5000, :pool-name "db-pool"}

ns> (hik/make-datasource (-> env :db))
ClassNotFoundException com.mysql.jdbc.jdbc2.optional.MysqlDataSource  java.net.URLClassLoader.findClass (URLClassLoader.java:381)
```

Indeed, there doesn't seem to be any com.mysql.jdbc.jdbc2 path. What am I missing?

**Comment by vigneshsarma** [comment]
I am seeing this to, one solution seems to be to change to order of setting `datasource-class-name`, https://github.com/tomekw/hikari-cp/blob/1.8.1/src/hikari_cp/core.clj#L184. If that is set after checking adapter, this should work. Right now if adapter is not set a jdbc-url is expected.

Shall I give a pr with that change?

**Comment by WorldsEndless** [comment]
If it would get things running, I'd certainly be in support of the change

**Comment by jstepien** [comment]
Thanks for filing the issue, @WorldsEndless. A PR would be great, @vigneshsarma, thanks a lot!
