### ISSUE TITLE
request:  support neo4j

### ISSUE THREAD

**Issue by tuddman** [tomekw/hikari-cp#71]
https://github.com/neo4j-contrib/neo4j-jdbc

**Comment by jstepien** [comment]
Patches are more than welcome!

**Comment by tuddman** [comment]
@tomekw I've added a [PR](https://github.com/tomekw/hikari-cp/pull/73)  for Neo4j to be added.  It works when setting the `jdbc-url` directly, which is sufficient for my use-cases.

I would appreciate if you could take a quick look and see what needs to be done for the neo4j driver to work as the others do in this library.  

Dziękuję

**Comment by tuddman** [comment]
closing: see https://github.com/tomekw/hikari-cp/pull/73

**Comment by jstepien** [comment]
Released as 2.1.0. Thanks for the patch!
