### ISSUE TITLE
MySQL driver property mixed-name translation (tinyInt1isBit)

### ISSUE THREAD

**Issue by bbsbb** [tomekw/hikari-cp#77]
This is a bit of a random one.
The MySQL connector supports a property called "tinyInt1isBit"(yes, really). Using a datasource configuration with :adapter "mysql", I couldn't see a way to format a clojure keyword that would be translated to such a property.
The "is" would always be an "Is". A workaround was to just use a :jdbc-url instead, which allows to inline the property correctly.
At a glance, mixed-name from org.tobereplaced.lettercase doesn't seem able to format a keyword to match as needed. Maybe we can document this with the goal of saving the next person down the line the odd half an hour.

**Comment by tomekw** [comment]
Oh, I'm more and more sure now everything MySQL-related is tricky and weird :) Would you be so kind to create a PR for this? :)

**Comment by bbsbb** [comment]
Let me know if you would like to do it another way. Take care.
