### ISSUE TITLE
Support for MySQL Connector/J 8+

### ISSUE THREAD

**Issue by tampix** [tomekw/hikari-cp#90]
Hello, and thanks for the library.

Currently, `"mysql"` `:adapter` datasource classname is `"com.mysql.jdbc.jdbc2.optional.MysqlDataSource"`.

From Connector/J 8+ onwards, the datasource changed to `com.mysql.cj.jdbc.MysqlDataSource` (see https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-api-changes.html)

As such, when using MySQL 8+, you have to either :
* use `:jdbc-url`
* use both `:adapter` and `:datasource-class-name`

It would be nice to have an adapter for mysql8 to handle that Connector/J change.

**Comment by tomekw** [comment]
Hello @tampix let me know if the PR works for you :)

**Comment by tomekw** [comment]
@tampix see `2.13.0` on Clojars.

**Comment by tampix** [comment]
Ah sorry, i didn't expect that fast of a reaction. Thanks a lot!
