### ISSUE TITLE
Push last changes to Clojars

### ISSUE THREAD

**Issue by munen** [tomekw/hikari-cp#96]
Dear hikari-cp maintainers,

First, let me say thank you very much for your great work!

Last year in April, you've upgraded HikariCP to a more current version (https://github.com/tomekw/hikari-cp/commit/824b77bbd52a5e1a852b482f297b258a4305a4ec), but the latest release on Clojars is older than the `master` branch. Could you release `master` to Clojars, please? Of course, if there's a blocker, I understand if that's not possible right now.

Thank you very much and kind regards :pray:

**Comment by tomekw** [comment]
Cheers @munen!

Done :)

**Comment by munen** [comment]
Sweet, thank you very much :pray:
